### ISSUE TITLE
SendTransactionParams type error in generated client.ts file

### ISSUE THREAD

**Issue by noliveira95** [algorand-devrel/learn-algokit-ts-client#7]
After cloning the repo and running the debug script, the generated client.ts file is throwing a type error:

```
Type '"skipWaiting" | "maxRoundsToWaitForConfirmation" | "populateAppCallResources" | "suppressLog"' does not satisfy the constraint 'keyof SendTransactionParams'.
Type '"populateAppCallResources"' is not assignable to type 'keyof SendTransactionParams'.
```

The error is found in client.ts on line 218

```
export type AppClientComposeExecuteParams = Pick<
  SendTransactionParams,
  'skipWaiting' | 'maxRoundsToWaitForConfirmation' | 'populateAppCallResources' | 'suppressLog'
>
```

Here's the current definition for SendTransactionParams (found on line 18 of transaction.d.ts):
```
export interface SendTransactionParams {
    skipSending?: boolean;
    skipWaiting?: boolean;
    atc?: AtomicTransactionComposer;
    suppressLog?: boolean;
    fee?: AlgoAmount;
    maxFee?: AlgoAmount;
    maxRoundsToWaitForConfirmation?: number;
}
```

It appears that "populateAppCallResources" is no longer a property of SendTransactionParams which is causing the issue. It may also be related to the Pick type definition.

**Comment by iskysun96** [comment]
Ah, this is because the algokit-utils dependency is outdated. Try updating the algokit-utils to the latest version inside of the project:

```bash
npm uninstall @algorandfoundation/algokit-utils
npm install @algorandfoundation/algokit-utils
```

"populationAppCallResources" was added later to allow automatic resource packing, automatically detecting all references needed for the transaction and including them in the reference array. 

I will also update this repo! thank you for bringing this to my attention!
